kumuluzee:
  name: apartments-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ApartmentDS
      connection-url: jdbc:postgresql://localhost:5432/apartments
      username: dbuser
      password: postgres
      max-pool-size: 20
  cors-filter:
    servlet:
      allow-origin: "http://localhost:4200"
      allow-subdomains: true
      supported-methods: "GET, POST, DELETE, HEAD, OPTIONS, PUT"
